language: cpp
compiler: clang

os: linux
dist: xenial
sudo: false

matrix:
  include:

    - env: TEST="Unit Tests"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 # we need this one for the libstdc++.
            - clang-6.0
            - ninja-build
            - python
            - python-pip
            - python3
            - python3-pip
            - libboost-python-dev
            - libtiff5-dev
            - libjpeg-dev
      install:
        - pip2 install -q --user setuptools nose2
        - pip3 install -q --user setuptools
        - pip3 install -q --user nose2
      script:
        - while sleep 2m; do echo "still building..."; done &
        - make setup >> build.log 2>&1
        - make LibCarla >> build.log 2>&1
        - make PythonAPI >> build.log 2>&1
        - kill %1
        - make check ARGS="--all --gtest_args=--gtest_filter=-*_mt"
      after_failure:
        - tail --lines=2000 build.log

    - env: TEST="MkDocs"
      install:
        - pip install -q --user mkdocs
      script:
        - mkdocs build --verbose --clean --strict --site-dir _site

notifications:
  email: false
